/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.dato_Persona;

/**
 *
 * @author rivera
 */
public class vista_Personas extends javax.swing.JFrame {
 dato_Persona dp=new dato_Persona();
 int id;
    /**
     * Creates new form vista_Personas
     */
    public vista_Personas() {
        initComponents();
       id=dp.idMaximo();
       idp.setText(""+id);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlID = new javax.swing.JLabel();
        jlNom = new javax.swing.JLabel();
        jlApat = new javax.swing.JLabel();
        jlApmat = new javax.swing.JLabel();
        jlSex = new javax.swing.JLabel();
        jlEdad = new javax.swing.JLabel();
        txtApmat = new javax.swing.JTextField();
        idp = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtAppat = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        bntGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlID.setText("Folio:");
        jPanel1.add(jlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jlNom.setText("Nombre:");
        jPanel1.add(jlNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jlApat.setText("Apellido Paterno:");
        jPanel1.add(jlApat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jlApmat.setText("Apellido Materno:");
        jPanel1.add(jlApmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jlSex.setText("Sexo:");
        jPanel1.add(jlSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        jlEdad.setText("Edad");
        jPanel1.add(jlEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));
        jPanel1.add(txtApmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, -1));
        jPanel1.add(idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, -1));
        jPanel1.add(txtAppat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, -1));
        jPanel1.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, -1));

        bntGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\rivera\\Documents\\NetBeansProjects\\SistemaMVC\\src\\icon\\diskette_save_saveas_1514.png")); // NOI18N
        bntGuardar.setText("Guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(bntGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        // TODO add your handling code here:
        //cuando presiones el boton debe de almacenar los datos al BD
       
        //dp.GuardarEmpleado("Juan", "Lopez", "Perez", 18, "M");
        dp.setNombre(txtNombre.getText());
        dp.setAppat(txtAppat.getText());
        dp.setApmat(txtApmat.getText());
        dp.setEdad(txtEdad.getText());
        dp.setSexo(txtSexo.getText());
        dp.GuardarEmpleado(txtNombre.getText(), 
                          txtAppat.getText(), 
                          txtApmat.getText(),
                          txtEdad.getText(),
                          txtSexo.getText());
        int id=dp.idMaximo();
        
        idp.setText(""+id);
        txtNombre.setText("");
        txtAppat.setText("");
        
    }//GEN-LAST:event_bntGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_Personas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntGuardar;
    private javax.swing.JTextField idp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlApat;
    private javax.swing.JLabel jlApmat;
    private javax.swing.JLabel jlEdad;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlNom;
    private javax.swing.JLabel jlSex;
    private javax.swing.JTextField txtApmat;
    private javax.swing.JTextField txtAppat;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
